export const plans = [
  {
    name: "Starter",
    price: "0",
    period: "Free forever",
    featured: false,
    cta: "Get started",
    ctaType: "outline",
    features: ["1,000 clicks / month", "50 active links", "Basic click analytics", "Device tracking", "7-day data retention"],
  },
  {
    name: "Pro",
    price: "19",
    period: "per month",
    featured: true,
    badge: "Most Popular",
    cta: "Start Pro",
    ctaType: "solid",
    features: ["100,000 clicks / month", "Unlimited links", "Conversion tracking", "Custom branded domain", "UTM builder", "90-day data retention"],
  },
  {
    name: "Business",
    price: "59",
    period: "per month",
    featured: false,
    cta: "Start Business",
    ctaType: "outline",
    features: ["Unlimited clicks", "Unlimited links", "All Pro features", "Team collaboration", "API access", "1-year data retention"],
  },
];